/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './router/__root'
import { Route as AuthenticatedRouteImport } from './router/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './router/_authenticated/index'
import { Route as AuthenticatedModelsRouteImport } from './router/_authenticated/models'
import { Route as AuthenticatedMcpsRouteImport } from './router/_authenticated/mcps'
import { Route as authLoginRouteImport } from './router/(auth)/login'
import { Route as AuthenticatedSettingsRouteRouteImport } from './router/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './router/_authenticated/users/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './router/_authenticated/settings/index'
import { Route as AuthenticatedModelsIndexRouteImport } from './router/_authenticated/models/index'
import { Route as AuthenticatedMcpsIndexRouteImport } from './router/_authenticated/mcps/index'
import { Route as AuthenticatedDataIndexRouteImport } from './router/_authenticated/data/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './router/_authenticated/apps/index'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './router/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './router/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './router/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './router/_authenticated/settings/account'
import { Route as AuthenticatedSettingsAboutRouteImport } from './router/_authenticated/settings/about'
import { Route as AuthenticatedAppsIdRouteImport } from './router/_authenticated/apps/$id'
import { Route as AuthenticatedModelsVirtualModelsIndexRouteImport } from './router/_authenticated/models/virtual-models/index'
import { Route as AuthenticatedModelsProvidersIndexRouteImport } from './router/_authenticated/models/providers/index'
import { Route as AuthenticatedModelsProviderModelsIndexRouteImport } from './router/_authenticated/models/provider-models/index'
import { Route as AuthenticatedModelsLogsIndexRouteImport } from './router/_authenticated/models/logs/index'
import { Route as AuthenticatedMcpsVirtualMcpsIndexRouteImport } from './router/_authenticated/mcps/virtual-mcps/index'
import { Route as AuthenticatedMcpsProvidersIndexRouteImport } from './router/_authenticated/mcps/providers/index'
import { Route as AuthenticatedMcpsProviderMcpsIndexRouteImport } from './router/_authenticated/mcps/provider-mcps/index'
import { Route as AuthenticatedMcpsLogsIndexRouteImport } from './router/_authenticated/mcps/logs/index'
import { Route as AuthenticatedModelsVirtualModelsIdRouteImport } from './router/_authenticated/models/virtual-models/$id'
import { Route as AuthenticatedModelsProvidersIdRouteImport } from './router/_authenticated/models/providers/$id'
import { Route as AuthenticatedModelsProviderModelsIdRouteImport } from './router/_authenticated/models/provider-models/$id'
import { Route as AuthenticatedModelsLogsIdRouteImport } from './router/_authenticated/models/logs/$id'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedModelsRoute = AuthenticatedModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMcpsRoute = AuthenticatedMcpsRouteImport.update({
  id: '/mcps',
  path: '/mcps',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedModelsIndexRoute =
  AuthenticatedModelsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedModelsRoute,
  } as any)
const AuthenticatedMcpsIndexRoute = AuthenticatedMcpsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedMcpsRoute,
} as any)
const AuthenticatedDataIndexRoute = AuthenticatedDataIndexRouteImport.update({
  id: '/data/',
  path: '/data/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAboutRoute =
  AuthenticatedSettingsAboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedAppsIdRoute = AuthenticatedAppsIdRouteImport.update({
  id: '/apps/$id',
  path: '/apps/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedModelsVirtualModelsIndexRoute =
  AuthenticatedModelsVirtualModelsIndexRouteImport.update({
    id: '/virtual-models/',
    path: '/virtual-models/',
    getParentRoute: () => AuthenticatedModelsRoute,
  } as any)
const AuthenticatedModelsProvidersIndexRoute =
  AuthenticatedModelsProvidersIndexRouteImport.update({
    id: '/providers/',
    path: '/providers/',
    getParentRoute: () => AuthenticatedModelsRoute,
  } as any)
const AuthenticatedModelsProviderModelsIndexRoute =
  AuthenticatedModelsProviderModelsIndexRouteImport.update({
    id: '/provider-models/',
    path: '/provider-models/',
    getParentRoute: () => AuthenticatedModelsRoute,
  } as any)
const AuthenticatedModelsLogsIndexRoute =
  AuthenticatedModelsLogsIndexRouteImport.update({
    id: '/logs/',
    path: '/logs/',
    getParentRoute: () => AuthenticatedModelsRoute,
  } as any)
const AuthenticatedMcpsVirtualMcpsIndexRoute =
  AuthenticatedMcpsVirtualMcpsIndexRouteImport.update({
    id: '/virtual-mcps/',
    path: '/virtual-mcps/',
    getParentRoute: () => AuthenticatedMcpsRoute,
  } as any)
const AuthenticatedMcpsProvidersIndexRoute =
  AuthenticatedMcpsProvidersIndexRouteImport.update({
    id: '/providers/',
    path: '/providers/',
    getParentRoute: () => AuthenticatedMcpsRoute,
  } as any)
const AuthenticatedMcpsProviderMcpsIndexRoute =
  AuthenticatedMcpsProviderMcpsIndexRouteImport.update({
    id: '/provider-mcps/',
    path: '/provider-mcps/',
    getParentRoute: () => AuthenticatedMcpsRoute,
  } as any)
const AuthenticatedMcpsLogsIndexRoute =
  AuthenticatedMcpsLogsIndexRouteImport.update({
    id: '/logs/',
    path: '/logs/',
    getParentRoute: () => AuthenticatedMcpsRoute,
  } as any)
const AuthenticatedModelsVirtualModelsIdRoute =
  AuthenticatedModelsVirtualModelsIdRouteImport.update({
    id: '/virtual-models/$id',
    path: '/virtual-models/$id',
    getParentRoute: () => AuthenticatedModelsRoute,
  } as any)
const AuthenticatedModelsProvidersIdRoute =
  AuthenticatedModelsProvidersIdRouteImport.update({
    id: '/providers/$id',
    path: '/providers/$id',
    getParentRoute: () => AuthenticatedModelsRoute,
  } as any)
const AuthenticatedModelsProviderModelsIdRoute =
  AuthenticatedModelsProviderModelsIdRouteImport.update({
    id: '/provider-models/$id',
    path: '/provider-models/$id',
    getParentRoute: () => AuthenticatedModelsRoute,
  } as any)
const AuthenticatedModelsLogsIdRoute =
  AuthenticatedModelsLogsIdRouteImport.update({
    id: '/logs/$id',
    path: '/logs/$id',
    getParentRoute: () => AuthenticatedModelsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/mcps': typeof AuthenticatedMcpsRouteWithChildren
  '/models': typeof AuthenticatedModelsRouteWithChildren
  '/apps/$id': typeof AuthenticatedAppsIdRoute
  '/settings/about': typeof AuthenticatedSettingsAboutRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/data/': typeof AuthenticatedDataIndexRoute
  '/mcps/': typeof AuthenticatedMcpsIndexRoute
  '/models/': typeof AuthenticatedModelsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/models/logs/$id': typeof AuthenticatedModelsLogsIdRoute
  '/models/provider-models/$id': typeof AuthenticatedModelsProviderModelsIdRoute
  '/models/providers/$id': typeof AuthenticatedModelsProvidersIdRoute
  '/models/virtual-models/$id': typeof AuthenticatedModelsVirtualModelsIdRoute
  '/mcps/logs/': typeof AuthenticatedMcpsLogsIndexRoute
  '/mcps/provider-mcps/': typeof AuthenticatedMcpsProviderMcpsIndexRoute
  '/mcps/providers/': typeof AuthenticatedMcpsProvidersIndexRoute
  '/mcps/virtual-mcps/': typeof AuthenticatedMcpsVirtualMcpsIndexRoute
  '/models/logs/': typeof AuthenticatedModelsLogsIndexRoute
  '/models/provider-models/': typeof AuthenticatedModelsProviderModelsIndexRoute
  '/models/providers/': typeof AuthenticatedModelsProvidersIndexRoute
  '/models/virtual-models/': typeof AuthenticatedModelsVirtualModelsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/apps/$id': typeof AuthenticatedAppsIdRoute
  '/settings/about': typeof AuthenticatedSettingsAboutRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/data': typeof AuthenticatedDataIndexRoute
  '/mcps': typeof AuthenticatedMcpsIndexRoute
  '/models': typeof AuthenticatedModelsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/models/logs/$id': typeof AuthenticatedModelsLogsIdRoute
  '/models/provider-models/$id': typeof AuthenticatedModelsProviderModelsIdRoute
  '/models/providers/$id': typeof AuthenticatedModelsProvidersIdRoute
  '/models/virtual-models/$id': typeof AuthenticatedModelsVirtualModelsIdRoute
  '/mcps/logs': typeof AuthenticatedMcpsLogsIndexRoute
  '/mcps/provider-mcps': typeof AuthenticatedMcpsProviderMcpsIndexRoute
  '/mcps/providers': typeof AuthenticatedMcpsProvidersIndexRoute
  '/mcps/virtual-mcps': typeof AuthenticatedMcpsVirtualMcpsIndexRoute
  '/models/logs': typeof AuthenticatedModelsLogsIndexRoute
  '/models/provider-models': typeof AuthenticatedModelsProviderModelsIndexRoute
  '/models/providers': typeof AuthenticatedModelsProvidersIndexRoute
  '/models/virtual-models': typeof AuthenticatedModelsVirtualModelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/_authenticated/mcps': typeof AuthenticatedMcpsRouteWithChildren
  '/_authenticated/models': typeof AuthenticatedModelsRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/apps/$id': typeof AuthenticatedAppsIdRoute
  '/_authenticated/settings/about': typeof AuthenticatedSettingsAboutRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/data/': typeof AuthenticatedDataIndexRoute
  '/_authenticated/mcps/': typeof AuthenticatedMcpsIndexRoute
  '/_authenticated/models/': typeof AuthenticatedModelsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/models/logs/$id': typeof AuthenticatedModelsLogsIdRoute
  '/_authenticated/models/provider-models/$id': typeof AuthenticatedModelsProviderModelsIdRoute
  '/_authenticated/models/providers/$id': typeof AuthenticatedModelsProvidersIdRoute
  '/_authenticated/models/virtual-models/$id': typeof AuthenticatedModelsVirtualModelsIdRoute
  '/_authenticated/mcps/logs/': typeof AuthenticatedMcpsLogsIndexRoute
  '/_authenticated/mcps/provider-mcps/': typeof AuthenticatedMcpsProviderMcpsIndexRoute
  '/_authenticated/mcps/providers/': typeof AuthenticatedMcpsProvidersIndexRoute
  '/_authenticated/mcps/virtual-mcps/': typeof AuthenticatedMcpsVirtualMcpsIndexRoute
  '/_authenticated/models/logs/': typeof AuthenticatedModelsLogsIndexRoute
  '/_authenticated/models/provider-models/': typeof AuthenticatedModelsProviderModelsIndexRoute
  '/_authenticated/models/providers/': typeof AuthenticatedModelsProvidersIndexRoute
  '/_authenticated/models/virtual-models/': typeof AuthenticatedModelsVirtualModelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/login'
    | '/mcps'
    | '/models'
    | '/apps/$id'
    | '/settings/about'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/apps/'
    | '/data/'
    | '/mcps/'
    | '/models/'
    | '/settings/'
    | '/users/'
    | '/models/logs/$id'
    | '/models/provider-models/$id'
    | '/models/providers/$id'
    | '/models/virtual-models/$id'
    | '/mcps/logs/'
    | '/mcps/provider-mcps/'
    | '/mcps/providers/'
    | '/mcps/virtual-mcps/'
    | '/models/logs/'
    | '/models/provider-models/'
    | '/models/providers/'
    | '/models/virtual-models/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/apps/$id'
    | '/settings/about'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/apps'
    | '/data'
    | '/mcps'
    | '/models'
    | '/settings'
    | '/users'
    | '/models/logs/$id'
    | '/models/provider-models/$id'
    | '/models/providers/$id'
    | '/models/virtual-models/$id'
    | '/mcps/logs'
    | '/mcps/provider-mcps'
    | '/mcps/providers'
    | '/mcps/virtual-mcps'
    | '/models/logs'
    | '/models/provider-models'
    | '/models/providers'
    | '/models/virtual-models'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/login'
    | '/_authenticated/mcps'
    | '/_authenticated/models'
    | '/_authenticated/'
    | '/_authenticated/apps/$id'
    | '/_authenticated/settings/about'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/apps/'
    | '/_authenticated/data/'
    | '/_authenticated/mcps/'
    | '/_authenticated/models/'
    | '/_authenticated/settings/'
    | '/_authenticated/users/'
    | '/_authenticated/models/logs/$id'
    | '/_authenticated/models/provider-models/$id'
    | '/_authenticated/models/providers/$id'
    | '/_authenticated/models/virtual-models/$id'
    | '/_authenticated/mcps/logs/'
    | '/_authenticated/mcps/provider-mcps/'
    | '/_authenticated/mcps/providers/'
    | '/_authenticated/mcps/virtual-mcps/'
    | '/_authenticated/models/logs/'
    | '/_authenticated/models/provider-models/'
    | '/_authenticated/models/providers/'
    | '/_authenticated/models/virtual-models/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  authLoginRoute: typeof authLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/models': {
      id: '/_authenticated/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof AuthenticatedModelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mcps': {
      id: '/_authenticated/mcps'
      path: '/mcps'
      fullPath: '/mcps'
      preLoaderRoute: typeof AuthenticatedMcpsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/models/': {
      id: '/_authenticated/models/'
      path: '/'
      fullPath: '/models/'
      preLoaderRoute: typeof AuthenticatedModelsIndexRouteImport
      parentRoute: typeof AuthenticatedModelsRoute
    }
    '/_authenticated/mcps/': {
      id: '/_authenticated/mcps/'
      path: '/'
      fullPath: '/mcps/'
      preLoaderRoute: typeof AuthenticatedMcpsIndexRouteImport
      parentRoute: typeof AuthenticatedMcpsRoute
    }
    '/_authenticated/data/': {
      id: '/_authenticated/data/'
      path: '/data'
      fullPath: '/data/'
      preLoaderRoute: typeof AuthenticatedDataIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/about': {
      id: '/_authenticated/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof AuthenticatedSettingsAboutRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/apps/$id': {
      id: '/_authenticated/apps/$id'
      path: '/apps/$id'
      fullPath: '/apps/$id'
      preLoaderRoute: typeof AuthenticatedAppsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/models/virtual-models/': {
      id: '/_authenticated/models/virtual-models/'
      path: '/virtual-models'
      fullPath: '/models/virtual-models/'
      preLoaderRoute: typeof AuthenticatedModelsVirtualModelsIndexRouteImport
      parentRoute: typeof AuthenticatedModelsRoute
    }
    '/_authenticated/models/providers/': {
      id: '/_authenticated/models/providers/'
      path: '/providers'
      fullPath: '/models/providers/'
      preLoaderRoute: typeof AuthenticatedModelsProvidersIndexRouteImport
      parentRoute: typeof AuthenticatedModelsRoute
    }
    '/_authenticated/models/provider-models/': {
      id: '/_authenticated/models/provider-models/'
      path: '/provider-models'
      fullPath: '/models/provider-models/'
      preLoaderRoute: typeof AuthenticatedModelsProviderModelsIndexRouteImport
      parentRoute: typeof AuthenticatedModelsRoute
    }
    '/_authenticated/models/logs/': {
      id: '/_authenticated/models/logs/'
      path: '/logs'
      fullPath: '/models/logs/'
      preLoaderRoute: typeof AuthenticatedModelsLogsIndexRouteImport
      parentRoute: typeof AuthenticatedModelsRoute
    }
    '/_authenticated/mcps/virtual-mcps/': {
      id: '/_authenticated/mcps/virtual-mcps/'
      path: '/virtual-mcps'
      fullPath: '/mcps/virtual-mcps/'
      preLoaderRoute: typeof AuthenticatedMcpsVirtualMcpsIndexRouteImport
      parentRoute: typeof AuthenticatedMcpsRoute
    }
    '/_authenticated/mcps/providers/': {
      id: '/_authenticated/mcps/providers/'
      path: '/providers'
      fullPath: '/mcps/providers/'
      preLoaderRoute: typeof AuthenticatedMcpsProvidersIndexRouteImport
      parentRoute: typeof AuthenticatedMcpsRoute
    }
    '/_authenticated/mcps/provider-mcps/': {
      id: '/_authenticated/mcps/provider-mcps/'
      path: '/provider-mcps'
      fullPath: '/mcps/provider-mcps/'
      preLoaderRoute: typeof AuthenticatedMcpsProviderMcpsIndexRouteImport
      parentRoute: typeof AuthenticatedMcpsRoute
    }
    '/_authenticated/mcps/logs/': {
      id: '/_authenticated/mcps/logs/'
      path: '/logs'
      fullPath: '/mcps/logs/'
      preLoaderRoute: typeof AuthenticatedMcpsLogsIndexRouteImport
      parentRoute: typeof AuthenticatedMcpsRoute
    }
    '/_authenticated/models/virtual-models/$id': {
      id: '/_authenticated/models/virtual-models/$id'
      path: '/virtual-models/$id'
      fullPath: '/models/virtual-models/$id'
      preLoaderRoute: typeof AuthenticatedModelsVirtualModelsIdRouteImport
      parentRoute: typeof AuthenticatedModelsRoute
    }
    '/_authenticated/models/providers/$id': {
      id: '/_authenticated/models/providers/$id'
      path: '/providers/$id'
      fullPath: '/models/providers/$id'
      preLoaderRoute: typeof AuthenticatedModelsProvidersIdRouteImport
      parentRoute: typeof AuthenticatedModelsRoute
    }
    '/_authenticated/models/provider-models/$id': {
      id: '/_authenticated/models/provider-models/$id'
      path: '/provider-models/$id'
      fullPath: '/models/provider-models/$id'
      preLoaderRoute: typeof AuthenticatedModelsProviderModelsIdRouteImport
      parentRoute: typeof AuthenticatedModelsRoute
    }
    '/_authenticated/models/logs/$id': {
      id: '/_authenticated/models/logs/$id'
      path: '/logs/$id'
      fullPath: '/models/logs/$id'
      preLoaderRoute: typeof AuthenticatedModelsLogsIdRouteImport
      parentRoute: typeof AuthenticatedModelsRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAboutRoute: typeof AuthenticatedSettingsAboutRoute
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAboutRoute: AuthenticatedSettingsAboutRoute,
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedMcpsRouteChildren {
  AuthenticatedMcpsIndexRoute: typeof AuthenticatedMcpsIndexRoute
  AuthenticatedMcpsLogsIndexRoute: typeof AuthenticatedMcpsLogsIndexRoute
  AuthenticatedMcpsProviderMcpsIndexRoute: typeof AuthenticatedMcpsProviderMcpsIndexRoute
  AuthenticatedMcpsProvidersIndexRoute: typeof AuthenticatedMcpsProvidersIndexRoute
  AuthenticatedMcpsVirtualMcpsIndexRoute: typeof AuthenticatedMcpsVirtualMcpsIndexRoute
}

const AuthenticatedMcpsRouteChildren: AuthenticatedMcpsRouteChildren = {
  AuthenticatedMcpsIndexRoute: AuthenticatedMcpsIndexRoute,
  AuthenticatedMcpsLogsIndexRoute: AuthenticatedMcpsLogsIndexRoute,
  AuthenticatedMcpsProviderMcpsIndexRoute:
    AuthenticatedMcpsProviderMcpsIndexRoute,
  AuthenticatedMcpsProvidersIndexRoute: AuthenticatedMcpsProvidersIndexRoute,
  AuthenticatedMcpsVirtualMcpsIndexRoute:
    AuthenticatedMcpsVirtualMcpsIndexRoute,
}

const AuthenticatedMcpsRouteWithChildren =
  AuthenticatedMcpsRoute._addFileChildren(AuthenticatedMcpsRouteChildren)

interface AuthenticatedModelsRouteChildren {
  AuthenticatedModelsIndexRoute: typeof AuthenticatedModelsIndexRoute
  AuthenticatedModelsLogsIdRoute: typeof AuthenticatedModelsLogsIdRoute
  AuthenticatedModelsProviderModelsIdRoute: typeof AuthenticatedModelsProviderModelsIdRoute
  AuthenticatedModelsProvidersIdRoute: typeof AuthenticatedModelsProvidersIdRoute
  AuthenticatedModelsVirtualModelsIdRoute: typeof AuthenticatedModelsVirtualModelsIdRoute
  AuthenticatedModelsLogsIndexRoute: typeof AuthenticatedModelsLogsIndexRoute
  AuthenticatedModelsProviderModelsIndexRoute: typeof AuthenticatedModelsProviderModelsIndexRoute
  AuthenticatedModelsProvidersIndexRoute: typeof AuthenticatedModelsProvidersIndexRoute
  AuthenticatedModelsVirtualModelsIndexRoute: typeof AuthenticatedModelsVirtualModelsIndexRoute
}

const AuthenticatedModelsRouteChildren: AuthenticatedModelsRouteChildren = {
  AuthenticatedModelsIndexRoute: AuthenticatedModelsIndexRoute,
  AuthenticatedModelsLogsIdRoute: AuthenticatedModelsLogsIdRoute,
  AuthenticatedModelsProviderModelsIdRoute:
    AuthenticatedModelsProviderModelsIdRoute,
  AuthenticatedModelsProvidersIdRoute: AuthenticatedModelsProvidersIdRoute,
  AuthenticatedModelsVirtualModelsIdRoute:
    AuthenticatedModelsVirtualModelsIdRoute,
  AuthenticatedModelsLogsIndexRoute: AuthenticatedModelsLogsIndexRoute,
  AuthenticatedModelsProviderModelsIndexRoute:
    AuthenticatedModelsProviderModelsIndexRoute,
  AuthenticatedModelsProvidersIndexRoute:
    AuthenticatedModelsProvidersIndexRoute,
  AuthenticatedModelsVirtualModelsIndexRoute:
    AuthenticatedModelsVirtualModelsIndexRoute,
}

const AuthenticatedModelsRouteWithChildren =
  AuthenticatedModelsRoute._addFileChildren(AuthenticatedModelsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedMcpsRoute: typeof AuthenticatedMcpsRouteWithChildren
  AuthenticatedModelsRoute: typeof AuthenticatedModelsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAppsIdRoute: typeof AuthenticatedAppsIdRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedDataIndexRoute: typeof AuthenticatedDataIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedMcpsRoute: AuthenticatedMcpsRouteWithChildren,
  AuthenticatedModelsRoute: AuthenticatedModelsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAppsIdRoute: AuthenticatedAppsIdRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedDataIndexRoute: AuthenticatedDataIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  authLoginRoute: authLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
